---
# Install Oracle Database
#
# for now fail if it's not a Red Hat based system
- name: Check OS ( Oracle )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'

#
- name: Install MS-SQL on Red Hat / CentOS
  import_tasks: install.yml
  tags: install

#
- name: Preparing sample data to interact with PXF
  import_tasks: prepare-sample-data-pxf.yml
  tags: install

#
- name: Uninstall MS-SQL on Red Hat / CentOS
  import_tasks: uninstall.yml
  tags: uninstall

#
- name: Upgrade MS-SQL on Red Hat / CentOS
  import_tasks: upgrade.yml
  tags: upgrade
