---
- name: Check OS ( MSSQL )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: config, install, uninstall, upgrade, setup, remove, prepare, create, delete


- name: Configure Firewall
  import_tasks: ext/config-firewall.yml
  tags: enable, config, install
  when: ( firewall is defined and firewall == true ) or ( mssql_all is defined and mssql_all == true )


- name: Install MS-SQL
  import_tasks: install.yml
  tags: setup, install
  when: ( db is defined and db == true ) or ( mssql_all is defined and mssql_all == true )


- name: Preparing sample data to interact with PXF
  import_tasks: prepare-sample-data-pxf.yml
  tags: prepare, install
  when: ( data is defined and data == true ) or ( mssql_all is defined and mssql_all == true )


- name: Uninstall MS-SQL
  import_tasks: uninstall.yml
  tags: delete, remove, uninstall
  when: ( db is defined and db == true ) or ( mssql_all is defined and mssql_all == true )


- name: Upgrade MS-SQL on Red Hat / CentOS
  import_tasks: upgrade.yml
  tags: upgrade
  when: ( db is defined and db == true ) or ( mssql_all is defined and mssql_all == true )

