#
- name: Creates directory for PXF sample script and queries
  become_user: root
  file:
    path: /root/pxf-queries/sqls
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

#
- name: Copy sample scripts to interact with PXF
  become_user: root
  template: src=pxf-queries/{{ item.fn }}.j2 dest={{ item.copy_dir }}/{{ item.fn }} owner=root group=root mode=0755 force=yes
  register: script_interact_pxf_copied
  with_items:
    - { fn: "00-change-sa-pass.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "01-create-db.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "02-create-table.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "03-remote-access.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "04-create-user.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "06-sample-connect.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "05-create-sample-table.sh", copy_dir: "/root/pxf-queries/" }

#
- debug: msg={{ script_interact_pxf_copied }}

#
- name: Copy sample query files to interact with PXF
  become_user: root
  template: src=pxf-queries/sqls/{{ item.fn }}.j2 dest={{ item.copy_dir }}/{{ item.fn }} owner=root group=root mode=0644 force=yes
  register: query_files_template_copied
  with_items:
    - { fn: "01-create-db.sql", copy_dir: "/root/pxf-queries/sqls/" }
    - { fn: "02-create-table.sql", copy_dir: "/root/pxf-queries/sqls/" }
    - { fn: "03-remote-access.sql", copy_dir: "/root/pxf-queries/sqls/" }
    - { fn: "04-create-user.sql", copy_dir: "/root/pxf-queries/sqls/" }
    - { fn: "05-create-sample-table.sql", copy_dir: "/root/pxf-queries/sqls/" }
    - { fn: "06-sample-connect.sql", copy_dir: "/root/pxf-queries/sqls/" }

#
- debug: msg={{ query_files_template_copied }}

#
- name: Run sample scripts to interact with PXF
  become_user: root
  shell: "sh /root/pxf-queries/{{ item.fn }}"
  register: sample_scripts_run
  with_items:
    - { fn: "00-change-sa-pass.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "01-create-db.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "02-create-table.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "03-remote-access.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "04-create-user.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "06-sample-connect.sh", copy_dir: "/root/pxf-queries/" }
    - { fn: "05-create-sample-table.sh", copy_dir: "/root/pxf-queries/" }

#
- debug: msg={{ sample_scripts_run }}

